# Generated by Django 3.2.25 on 2024-04-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPortfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram', models.TextField()),
                ('git_hub_link', models.TextField()),
                ('cv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StackTech',
            fields=[
                ('id_st', models.AutoField(primary_key=True, serialize=False)),
                ('stack', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id_t', models.AutoField(primary_key=True, serialize=False)),
                ('name_t', models.TextField()),
                ('banner_t', models.TextField()),
                ('login_t', models.TextField()),
                ('password_t', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id_sup', models.AutoField(primary_key=True, serialize=False)),
                ('name_sup', models.TextField()),
                ('surname_sup', models.TextField()),
                ('secondname_sup', models.TextField()),
                ('age_sup', models.IntegerField()),
                ('date_of_birth_sup', models.DateField()),
                ('teams_sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('surname_p', models.TextField()),
                ('name_p', models.TextField()),
                ('secondname_p', models.TextField()),
                ('age_p', models.TextField()),
                ('date_of_birth_p', models.DateField()),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp.contactsportfolio')),
                ('stack_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp.stacktech')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp.supervisors')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackapp.teams')),
            ],
        ),
    ]
