# Generated by Django 3.2.25 on 2024-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsportfolio',
            name='git_hub_link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactsportfolio',
            name='telegram',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='participants',
            name='age_p',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='participants',
            name='name_p',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='participants',
            name='secondname_p',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='participants',
            name='surname_p',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='name_sup',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='secondname_sup',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supervisors',
            name='surname_sup',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='teams',
            name='banner_t',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teams',
            name='login_t',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name_t',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teams',
            name='password_t',
            field=models.CharField(max_length=100),
        ),
    ]
