# Generated by Django 3.2.25 on 2024-04-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0002_auto_20240420_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='stack_tech',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='team',
        ),
        migrations.RemoveField(
            model_name='supervisors',
            name='teams_sup',
        ),
        migrations.DeleteModel(
            name='ContactsPortfolio',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.DeleteModel(
            name='StackTech',
        ),
        migrations.DeleteModel(
            name='Supervisors',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
