# Generated by Django 3.2.25 on 2024-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0004_contactsportfolio_participants_stacktech_supervisors_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='secondname_p',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
