# Generated by Django 3.2.25 on 2024-04-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0005_alter_participants_secondname_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackapp.supervisors'),
        ),
    ]
