# Generated by Django 3.2.25 on 2024-04-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0006_alter_participants_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='capitan',
            field=models.BooleanField(default=False),
        ),
    ]
